plugins:
  kyverno: false

# Key/value pairs that are attached to all resources.
annotations: {}

serviceMonitor:
  # HonorLabels chooses the metrics labels on collisions with target labels
  honorLabels: false
  # allow to override the namespace for serviceMonitor
  namespace:
  # labels to match the serviceMonitorSelector of the Prometheus Resource
  labels: {}
  # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
  relabelings: []
  # see serviceMonitor.relabelings
  metricRelabelings: []

kyverno:
  serviceMonitor:
    # HonorLabels chooses the metrics labels on collisions with target labels
    honorLabels: false
    # see serviceMonitor.relabelings
    relabelings: []
    # see serviceMonitor.relabelings
    metricRelabelings: []

grafana:
  # namespace for configMap of grafana dashboards
  namespace:
  dashboards:
    # Enable the deployment of grafana dashboards
    enabled: true
    # Label to find dashboards using the k8s sidecar
    label: grafana_dashboard
    value: "1"
  folder:
    # Annotation to enable folder storage using the k8s sidecar
    annotation: grafana_folder
    # Grafana folder in which to store the dashboards
    name: Policy Reporter

policyReportDetails:
  firstStatusRow:
    height: 8
  secondStatusRow:
    enabled: true
    height: 2
  statusTimeline:
    enabled: true
    height: 8
  passTable:
    enabled: true
    height: 8
  failTable:
    enabled: true
    height: 8
  warningTable:
    enabled: true
    height: 4
  errorTable:
    enabled: true
    height: 4

clusterPolicyReportDetails:
  statusRow:
    height: 6
  statusTimeline:
    enabled: true
    height: 8
  passTable:
    enabled: true
    height: 8
  failTable:
    enabled: true
    height: 8
  warningTable:
    enabled: true
    height: 4
  errorTable:
    enabled: true
    height: 4

policyReportOverview:
  failingSummaryRow:
    height: 8
  failingTimeline:
    height: 10
  failingPolicyRuleTable:
    height: 10
  failingClusterPolicyRuleTable:
    height: 10
