{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels: {{- include "kyvernoplugin.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  name: {{ include "kyvernoplugin.fullname" . }}
  namespace: {{ include "kyvernoplugin.namespace" . }}
spec:
  podSelector:
    matchLabels: {{- include "kyvernoplugin.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "ui.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 8080
  {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
