apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ui.fullname" . }}-config
  namespace: {{ include "ui.namespace" . }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
data:
  config.yaml: |-
    logSize: {{ .Values.log.size }}
    displayMode: {{ .Values.displayMode | quote }}
    refreshInterval: {{ .Values.refreshInterval }}
    clusterName: {{ .Values.clusterName | quote }}
    views:
      dashboard:
        policyReports: {{ .Values.views.dashboard.policyReports }}
        clusterPolicyReports: {{ .Values.views.dashboard.clusterPolicyReports }}
      logs: {{ .Values.views.logs }}
      policyReports: {{ .Values.views.policyReports }}
      clusterPolicyReports: {{ .Values.views.clusterPolicyReports }}
      kyvernoPolicies: {{ .Values.views.kyvernoPolicies }}
      kyvernoVerifyImages: {{ .Values.views.kyvernoVerifyImages }}
    {{- with .Values.clusters }}
    clusters:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.labelFilter }}
    labelFilter:
      {{- toYaml . | nindent 4 }}
    {{- end }}

    {{- with .Values.redis }}
    redis:
      {{- toYaml . | nindent 6 }}
    {{- end }}

