apiVersion: v2
name: policy-reporter
description: |
  K8s PolicyReporter watches for wgpolicyk8s.io/v1alpha1.PolicyReport resources.
  It creates Prometheus Metrics and can send rule validation events to different targets like Loki, Elasticsearch, Slack or Discord

type: application
version: 0.20.2
appVersion: 0.12.0

dependencies:
  - name: monitoring
    condition: monitoring.enabled
    repository: ""
    version: "0.3.0"
  - name: ui
    condition: ui.enabled
    repository: ""
    version: "0.4.1"
