apiVersion: v2
name: policy-reporter
description: |
  K8s PolicyReporter watches for wgpolicyk8s.io/v1alpha1.PolicyReport resources.
  It creates Prometheus Metrics and can send rule validation events to different targets like Loki, Elasticsearch, Slack or Discord

type: application
version: 1.8.9
appVersion: 1.8.5

dependencies:
  - name: monitoring
    condition: monitoring.enabled
    repository: ""
    version: "1.4.3"
  - name: ui
    condition: ui.enabled
    repository: ""
    version: "1.8.5"
  - name: kyvernoPlugin
    condition: kyvernoPlugin.enabled
    repository: ""
    version: "0.5.2"
