apiVersion: v2
name: policy-reporter
description: |
  Policy Reporter watches for PolicyReport Resources.
  It creates Prometheus Metrics and can send rule validation events to different targets like Loki, Elasticsearch, Slack or Discord

type: application
version: 2.5.0
appVersion: 2.3.0

icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
home: https://kyverno.github.io/policy-reporter
sources:
  - https://github.com/kyverno/policy-reporter
maintainers:
  - name: Frank Jogeleit

dependencies:
  - name: monitoring
    condition: monitoring.enabled
    version: "2.0.1"
  - name: ui
    condition: ui.enabled
    version: "2.3.1"
  - name: kyvernoPlugin
    condition: kyvernoPlugin.enabled
    version: "1.2.0"
